name: Code-Troopers blog
description: Le blog de l'équipe Code-Troopers
url: http://code-troopers.com
baseurl: /

source: app
destination: generated
exclude: ['bower_components','styles','images','scripts']
gems: [jekyll-paginate, jekyll-asciidoc]
paginate: 6
paginate_path: "/blog/page:num/"

highlights: pygments

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=class
    - icons=font
