name: Code-Troopers blog
description: Le blog de l'équipe Code-Troopers
url: http://code-troopers.com
baseurl: /

source: app
destination: .generated
exclude: ['bower_components','styles','images','scripts']
gems: [jekyll-paginate]
paginate: 6
paginate_path: "/blog/page:num/"
