baseurl: "/"
languageCode: "fr-fr"
title: "Code-Troopers - Vous avez une idée, nous la réalisons"
archetypeDir: "site/archetypes"
contentDir: "site/content"
dataDir: "site/data"
layoutDir: "site/layouts"
staticDir: "site/static"
themesDir: "site/themes"
paginate: 9
pygmentsUseClasses: true