baseurl: "/"
languageCode: "fr-fr"
title: "Code-Troopers - Vous avez une idée, nous la réalisons"
archetypeDir: "site/archetypes"
contentDir: "site/content"
dataDir: "site/data"
layoutDir: "site/layouts"
staticDir: "site/static"
themesDir: "site/themes"
paginate: 9
pygmentsUseClasses: true
SectionPagesMenu: "main"
relativeURLs: true
menu:
  main:
    - Identifier: "skills"
      Name: "Compétences"
      URL: "/#skills"
      Weight: 1
    - Identifier: "portfolio"
      Name: "Réalisations"
      URL: "/#portfolio"
      Weight: 2
    - Identifier: "casting"
      Name: "Casting"
      URL: "/#casting"
      Weight: 3
    - Identifier: "contact"
      Name: "Contact"
      URL: "/#contact"
      Weight: 4
    - Identifier: "blog"
      Name: "Blog"
      URL: "/blog"
      Pre: "blog"
      Weight: 5